Small error fixes
Mattwmaster58/playwright_stealth pull request #3
Opened 2024-10-02 18:29 UTC by andriibuda

Hello, thank you for deciding to update and revitalise the `playwright-stealth` that was abandoned for almost a year. You've done a really cool job 🔥

But during the adding of the package via `poetry add git+https://github.com/mattwmaster58/playwright_stealth`, it failed because of the invalid licence param in `the pyproject.toml`. I added a MIT licence there.
<img width="1321" alt="image" src="https://github.com/user-attachments/assets/60e602b6-ff0a-4c67-928c-1da5d08ea366">

Also after the first run of the library I encountered an error - not all js-files were included to the `package_data`, I also updated it:
<img width="1383" alt="image" src="https://github.com/user-attachments/assets/a37f723d-4851-4943-9266-d8d5ac19507c">
 
 By the way, how do you think, @Mattwmaster58, maybe change `js/mitigations/*.js` to `js/**/*.js`?

2024-10-02 18:50 UTC, Mattwmaster58 commented
Oh nice, I knew the packaging wasn't working at the moment, this looks like it'll cross that off the list

2024-10-02 18:55 UTC, Mattwmaster58 commented
> By the way, how do you think, @Mattwmaster58, maybe change js/mitigations/*.js to js/**/*.js?

Yes, this seems like a wise change

2024-10-02 18:56 UTC, Mattwmaster58 requested changes
package_data

2024-10-02 19:32 UTC, andriibuda commented
Thank you for the feedback 🙂

Just updated the `setup.py`, now it will include all JS-files from subdirectories as well

2024-10-04 02:46 UTC, Mattwmaster58 approved these changes

2024-10-04 02:47 UTC, merged

2024-10-04 02:48 UTC, Mattwmaster58 commented
Merged this to main without testing, because either way packaging was broken and I intend to look at this over the next few days anyway. 

Thanks for the contribution!